### ISSUE TITLE
Special characters not rendering correctly

### ISSUE THREAD

**Issue by mkturner** [tylucaskelley/kanye-ipsum#1]
Hi, thanks for kanye-ipsum. Its a dope concept.

I was looking to use it to generate text for sites in my portfolio, but I noticed that characters are used without their [name & number codes](http://designerstoolbox.com/designresources/html/). Thus they render as gibberish.

I started to edit the quotes with correct codes and issue a pull request ~~though it seems that these quotes are not stored in the repo; They are being scraped from various sites online~~. (EDIT: done! see below.)

Please advise on a fix/workaround.

**Comment by mkturner** [comment]
Nevermind, I found them.

**Comment by tylucaskelley** [comment]
merged PR
